wellcomecollection/content-api

pipeline/src/config/articles.ts
pipeline/src/transformers/article.ts
pipeline/src/types/index.ts

Realised it still had a different name in `query` and `display`, so fixing that.

Rename published to publicationDate

---

api/src/controllers/articles.ts

`?sort=publication.date&sortOrder=asc`, for example.
Defaults to `_score`. If no `sortOrder` is specified, defaults to `desc`. 
As specified in the RFC, only sorting by date or relevance.

Add sorting by date

---

pipeline/src/config.ts
pipeline/src/handler.ts
pipeline/src/helpers/elasticsearch.ts
pipeline/src/indices/articles.ts
pipeline/src/indices/index.ts
pipeline/src/lambda.ts

I moved some stuff around when I was thinking about what config to inject via the environment - this makes the helper functions fairly agnostic as to their use, and puts code/config specific to our use case at the top level.

Refactoring ahead of infra

---

common/data/formats.ts
pipeline/src/transformers/article.ts
pipeline/src/types/prismic/formats.ts
pipeline/src/types/transformed/index.ts

Some articles don't have a defined format, in which case we always want it to be Article.
Twinned with [wc.org changes](https://github.com/wellcomecollection/wellcomecollection.org/pull/9577)
Relates to #9575

Set a default format of Article

---

api/src/controllers/articles.ts

[Feedback on the new content api](https://wellcome.slack.com/archives/C3N7J05TK/p1681217319076659?thread_ts=1681216275.074579&cid=C3N7J05TK) indicates that our current query isn't looking at the fully analysed text for some fields. 
For example, searching for **parkinsons** doesn't return results where **parkinson's** (with an apostrophe) appears in the article's `body`.   
While the basic, top-level `text` field's analyser won't be able to handle nuances like apostrophes, the `body` field has subfields which use the `english_shingle_analyzer` and `english_cased_analyzer` analysers, which _should_ be able to cope. The problem is that we're not currently pointing the query at those subfields.
This PR updates the query with wildcards at the end of the top-level field names, ensuring that we …

use wildcards to make sure we're querying all of the useful subfields

---

pipeline/src/indices/articles.ts
pipeline/src/transformers/article.ts
pipeline/src/types/index.ts

At the moment we're not indexing body text beyond the first paragraph of an article's body, so a lot of documents with relevant keywords in their body are being missed! For example, [_Are doctors medical detectives?_](https://wellcomecollection.org/articles/XKIXNRAAAJsnbmFE) is missing from a search for **parkinsons** because the word only appears after the second paragraph.
This PR indexes _all_ of the body's `text` fields, and adds in `quoteV2`s and `standfirst`s for good measure.
I've also shuffled a couple of the filters in the mapping - these should only have a minor positive effect on scoring.

index the complete article body

---

api/server.ts
common/services/elasticsearch.ts
infrastructure/locals.tf
infrastructure/pipeline.tf
infrastructure/pipeline_stack/elastic_cluster.tf
infrastructure/pipeline_stack/variables.tf
pipeline/src/lambda.ts
pipeline/src/local.ts

I was wrong about this being a bug in the ES client - the issue was that (a) I'd forgotten to configure the PrivateLink traffic filters for the cluster, and (b) the way we chose which endpoint to use was indirect/unclear and think had changed inadvertently, obscuring the actual issue and leading me on a wild goose chase.

Use PrivateLink again

---

.gitignore
infrastructure/.terraform.lock.hcl
infrastructure/api_stack/api_gateway.tf
infrastructure/api_stack/certificate.tf

For https://github.com/wellcomecollection/platform/issues/5677
I haven't done any state wrangling for this change yet – when I plan locally, Terraform wants to tear down a bunch of Lambda resources that are presumably in somebody's local branch somewhere.

Use the new Terraform module to create ACM certificates

---

api/src/queries/articles.ts
pipeline/src/indices/articles.ts

As per https://github.com/wellcomecollection/content-api/pull/40#issuecomment-1517814993
I've already done the requisite around shuffling of indices to change the (live) mapping of `id` to `keyword`, as for some reason it was previously a `text` field.

Query the article ID

---

api/src/controllers/articles.ts
api/src/controllers/validation.ts
api/src/helpers/elastic.ts
api/src/helpers/index.ts
api/src/helpers/requests.ts
api/src/helpers/responses.ts
api/src/queries/articles.ts
api/src/queries/faceting.ts
api/src/types/index.ts
api/src/types/responses.ts
api/test/__snapshots__/query.test.ts.snap
api/test/__snapshots__/responses.test.ts.snap
api/test/faceting.test.ts
api/test/query.test.ts
api/test/responses.test.ts
api/test/validation.test.ts
pipeline/src/indices/articles.ts
pipeline/src/transformers/article.ts
pipeline/src/types/index.ts
pipeline/test/transformers/__snapshots__/article.test.ts.snap

Big diff *but* it's mostly tests and comments! 😇 
This PR adds aggregations to the content API. The complexity of the change is due to the need to return results that can be used to build a [faceted](https://en.wikipedia.org/wiki/Faceted_search) search interface. The details of those requirements are explained in [RFC 037](https://github.com/wellcomecollection/docs/tree/main/rfcs/037-api-faceting-principles).
The Catalogue API achieves this behaviour through many classes spread across the application, and uses the https://github.com/sksamuel/elastic4s DSL to construct the queries. This code is extremely complex, confusing, and poorly understood (I can say that because I wrote it!)
Most of that code was written during the process of understanding the desired behaviour, rather than after we …

Add aggregations with correct faceting behaviour

---

pipeline/src/helpers/index.ts
pipeline/src/helpers/prismic.ts
pipeline/src/helpers/type-guards.ts
pipeline/src/transformers/article.ts
pipeline/src/types/prismic/articles.ts
pipeline/src/types/prismic/body.ts
pipeline/src/types/prismic/contributors.ts
pipeline/src/types/prismic/formats.ts
pipeline/src/types/prismic/images.ts
pipeline/src/types/prismic/index.ts
pipeline/src/types/prismic/series.ts
pipeline/test/fixtures/prismic-snapshots.ts
pipeline/test/fixtures/prismic.ts
pipeline/test/handler.test.ts
pipeline/test/prismic-helpers.test.ts

We've switched to namespacing everything in the front-end; let's do the same here.
For https://github.com/wellcomecollection/wellcomecollection.org/issues/9797

Make our Prismic imports consistent

---

infrastructure/pipeline_stack/elastic_users.tf

This will prevent pain further down the line. It's already applied.

Add service permissions for `events*` indices

---

api/src/controllers/events.ts

sorts #83 
Was missing `paginationElasticBody` - and now `page` and `pageSize` can be adjusted accordingly.

paginationElasticBody implemented - fixing pagination and pageSize

---

pipeline/src/indices/events.ts
pipeline/src/transformers/eventDocument.ts
pipeline/src/types/transformed/index.ts
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap

- Adds the additional queries to the events mapping index, as well as ensuring dynamic is set to strict.
- `times: {startDateTime: Date[]` type added to ElasticsearchEventDocument
- The times property then added to the transformEventDocument in the eventDocument. 
`events?sort=times.startDateTime&sortOrder=desc` and `events?sort=times.startDateTime&sortOrder=asc` should now display events in order accordingly.

Fixes sorting asc/desc order

---

api/src/controllers/events.ts
api/src/queries/events.ts

Allows for query strings to be passed in and return some more valuable results, mostly based on the `id` and the `title`, but a little bit on the `caption` as well (I went for what level we went for `standfirst` in articles (`^10`). This is just to _have_ something and the metrics could be revisited.
```
cd api
yarn install & yarn dev
```
go to `localhost:3000/events?query=[string of your choice]`
Do the results look slightly relevant? Are they returning something different than the default set of results?
I can't really think of any as this is very much a work in progress and shouldn't affect anything else.

Very basic query for events

---

api/config.ts
api/src/app.ts
api/src/controllers/healthcheck.ts
api/src/controllers/index.ts
infrastructure/api_stack/api_service.tf
infrastructure/api_stack/variables.tf

This change adds a [HTTP healthcheck for a services target group](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html). The reason for this change is to avoid downtime during deploys, as at present the TCP healthcheck will only wait for nginx to be able to open a connection although the underlying service may not yet have started.
> [!NOTE]
> The healthcheck endpoint does not detect if the elasticsearch client is able to successfully make connections, so does not fully report service health, we should add this in a future PR.
A request to `/management/healthcheck` should result in a HTTP 200 response with the body:
```json
{
"status": "ok",
"config": {
"pipelineDate": "2023-03-24",
"articlesIndex": "articles",
"eventsIndex": "events", …
```

Add naive healthcheck endpoint for content-api

---

pipeline/src/transformers/article.ts
pipeline/src/transformers/eventDocument.ts
pipeline/src/transformers/utils.ts
pipeline/src/types/prismic/eventDocuments.ts
pipeline/src/types/transformed/eventDocument.ts
pipeline/src/types/transformed/index.ts
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap

https://github.com/wellcomecollection/content-api/issues/92
Following Raph's work on https://github.com/wellcomecollection/wellcomecollection.org/issues/10587 it came up that some properties are missing in the `display` part of the eventDocuments. This PR adds them in
`audiences` is in this format
```
{
type: "EventAudience",
id: PrismicId, // string
label: title, // string
}
``` 
`series` like so
```
{
"contributors": [
"Land Body Ecologies",
"The Hub",
],
"id": "ZFt3UBQAAMFmEIya",
"title": "Land Body Ecologies Festival",
},
```
Reindex has not been performed yet. Once this is approved we'll reindex and will be able to check that the documents look as expected. The event stuff is behind a toggle but the API is up, can be used for testing as well
Snapshots have been updated and look as …

add audiences and series to display object

---

pipeline/src/graph-queries/eventDocuments.ts
pipeline/src/transformers/eventDocument.ts
pipeline/src/types/prismic/eventDocuments.ts
pipeline/src/types/transformed/eventDocument.ts
pipeline/src/types/transformed/index.ts
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap

As discussed, we're adding a property to indicate an event is a "child", ie. part of the schedule of a "parent" event, to be excluded from search results as the MVP stage https://github.com/wellcomecollection/content-api/issues/93
Also adding online/in-venue booking status/availability https://github.com/wellcomecollection/content-api/issues/96
See updated test snapshots 
Once the changes are reflected in the index, FE will be able to display booking status on the event card in search
We can also exclude delisted events (without pictures) from search 
Feature behind a toggle so no risk

add booking info in times objects + childScheduledEvent at root level

---

api/src/controllers/events.ts
api/src/helpers/requests.ts
api/src/helpers/responses.ts
api/src/queries/events.ts
api/src/queries/faceting.ts
api/test/__snapshots__/query.test.ts.snap
api/test/query.test.ts

https://github.com/wellcomecollection/content-api/issues/71
Adds filters and aggregations to `/events` search endpoint 
Stage
`https://api-stage.wellcomecollection.org/content/v0/events?aggregations=format%2Caudience%2CisOnline%2Cinterpretation`
Filtered by interpretation=Auto-captioned and format=Discussion
`https://api-stage.wellcomecollection.org/content/v0/events?aggregations=format%2Caudience%2CisOnline%2Cinterpretation&interpretation=X2jPiRMAACIA8Vzo&format=Wd-QYCcAACcAoiJS&pageSize=1` 
Ability to filter event searches
Still behind a toggle

add filter/aggs to events endpoint

---

pipeline/src/indices/events.ts
pipeline/src/transformers/eventDocument.ts
pipeline/src/types/prismic/eventDocuments.ts
pipeline/src/types/transformed/eventDocument.ts
pipeline/src/types/transformed/index.ts
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap

https://github.com/wellcomecollection/content-api/issues/107
Adds `isAvailableOnline` to eventDocuments so that we can display the value on the event search result cards, and filter and aggregate based on it
⚠️ Reindex not performed yet
See test snapshot
Together with https://github.com/wellcomecollection/content-api/issues/109 we'll be able to search for/filter events that were recorded and can be watched online
Behind a toggle so minimal risk, can delete index and recreate it if something goes wrong

add isAvailableOnline to display, filter and aggValues for eventDocument

---

pipeline/README.md
pipeline/src/transformers/eventDocument.ts

`isAvailableOnline: null` is now transformed to `isAvailableOnline: false`.
I've also added info to the README on how to run reindexes.
Have a look on ES or run locally to find formerly `null` values being `false`
Relevant results are found and people are happy
It's all behind a toggle so pretty safe and can easily be reverted.
---
Reindex was run

Make null equal false for isAvailableOnline

---

api/src/controllers/events.ts
api/src/queries/events.ts

- Adds `isAvailableOnline` as a valid boolean param
- Adds a paramsValidator function, currently only checks `isAvailableOnline` so open to simplifying but thought it made things more readable
Run locally and try an array of queries, such as
`http://localhost:3000/events?format=Wd-QYCcAACcAoiJS`, (should return 163 results)
`http://localhost:3000/events?format=Wd-QYCcAACcAoiJS&isAvailableOnline=true`, (should return 50 results)
`http://localhost:3000/events?format=Wd-QYCcAACcAoiJS&isAvailableOnline=test`, (should return a Bad Request)
`http://localhost:3000/events?format=Wd-QYCcAACcAoiJS&isAvailableOnline=true,test` (should return a Bad Request)
Users are finding it useful and it's in use.
Behind a toggle and easy to revert, so no risks per say

Add isAvailableOnline to API and validate its value

---

pipeline/src/transformers/eventDocument.ts
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap

Make the boolean isAvailableOnline agg bucket more like the others, with a label and type
Run content-api locally
Hit `http://localhost:3000/events?aggregations=isAvailableOnline%2Cformat%2Caudience%2CisOnline%2Cinterpretation`
See that the response contains 
```
"aggregations": {
... other aggregations,
"isAvailableOnline": {
"buckets": [
{
"data": {
"type": "OnlineAvailabilityBoolean",
"value": true,
"label": "Catch-up event"
},
"count": 24,
"type": "AggregationBucket"
},
{
"data": {
"type": "OnlineAvailabilityBoolean",
"value": false,
"label": "Catch-up event"
},
"count": 3,
"type": "AggregationBucket"
}
],
"type": "Aggregation"
},
}
```
Raph's types are happier in wc.org
N/A

make isAvailableOnline agg bucket more like the others, ie type+label

---

api/src/controllers/utils.ts
api/test/utils.test.ts

https://github.com/wellcomecollection/content-api/issues/133
[Slack thread](https://wellcome.slack.com/archives/CUA669WHH/p1722266021986019)
LE&E brought to our attention that a library user was able to request an item for a Sunday.
-> On Friday between 11pm and midnight during BST, a timezone loophole caused the Sunday to be mistaken for a Monday, thus to not be removed from the available date list.
This is fixed by explicitly setting the timezone as `["Europe/London"]` when we extract the day of the week from the timestamp
The tests have been duplicated to cover the same scenarios both in UTC and BST times of the year.
An additional test case specifically covers the "around midnight on a Friday during BST" scenario
When placing an item request around midnight on a Friday during BST, the …

get day name in London timezone + test around midnight

---

.github/workflows/stale.yml

The stale PR workflow will run every 5 minutes (temporarily) using a workflow stored in https://github.com/wellcomecollection/.github
The schedule will go back to everyday Monday-Thursday once we assert this works just as well as duplicating the workflows across the repos that run it
Once this is merged, we should see within 5 minutes a Github action being triggered to run the shared workflow stored in the `.github` repo
The github action gets triggered and runs successfully using a workflow from a different repo
Minimal. Worst case scenario, stale PRs do not get spotted and closed

Use shared stale pr workflow

---

pipeline/README.md

Following the creation of the diagram for the All Search RFC, I thought it'd be good to have a generic version added in here for future reference.
[See README file](https://github.com/wellcomecollection/content-api/blob/a211d6a408717abac81dceb24abfbb87bf849463/pipeline/README.md)

Add ETL diagram to pipeline README

---

pipeline/src/scripts/testTransformer.ts
pipeline/src/transformers/addressables/book.ts
pipeline/src/types/prismic/addressables/books.ts
pipeline/src/types/prismic/books.ts
pipeline/src/types/transformed/index.ts

First go at the first of the addressable transformers needed for #156
`cd pipeline && yarn testTransformer --type book`
We're a step closer to being able to display addressable content in 'All search'
Can't think of any

Add addressable book transformer

---

pipeline/package.json
pipeline/src/event.ts
pipeline/src/handler.ts
pipeline/src/indices/addressables.ts
pipeline/src/indices/index.ts
pipeline/src/local.ts
pipeline/src/transformers/addressables.ts

#153  and #156
Adds necessary types and helpers to index Addressables.
I've also added the "parent" transformer file that sends documents to their relevant transformer.
We won't index right away I think, which is why some code is commented out, so no need to test the indexing as part of this PR. As long as TS and tests are happy, so are we for now I think?
Eases further work
This isn't used yet so shouldn't have risks.

Update types and add helpers to index addressables

---

api/nodemon.json
api/package.json
api/src/controllers/error.ts
api/src/controllers/utils.ts
yarn.lock

Following testing the requesting date picker for the holiday closure, a bug was identified whereby:
- exceptional closed days are saved as "midnight on the closed day" (in Prismic and the venues index)
- we filter for exceptional closed days that are in the past (as irrelevant)
- however, if you run the code on an exceptional closed day, anytime after midnight (ie. all day basically) the date comparison which includes the time will deem the closed day to be in the past and ignore it
- the exceptional closed day is then incorrectly listed as an open day 
FIX: don't filter for closed days that are in the past
ALSO
- fixed the error handler that was complaining about res.status not a function
- added nodemon for hot reload
Set the `dateNow` in `api/src/controllers/utils.ts` to a date when …

fix exceptional closure bug

---

api/src/queries/addressables.ts

For #166 
Adds the API query for addressables. It doesn't include any filtering or aggregation, in line with what was [decided in the RFC](https://github.com/wellcomecollection/docs/tree/main/rfcs/062-content-api-all-search#background-information).
This query isn't connected to a controller (coming in #167) so doesn't require testing yet because it isn't doing anything.
n/a
n/a

Add addressables API query

---

infrastructure/terraform.tf

Updated Terraform to v1.10.1 and this was required ([see github ticket](https://github.com/hashicorp/terraform/issues/36124))
The update means we can't run `terraform [command]` anymore and have to go through `./run_terraform.sh [command]` instead as that's where it fetches the required secrets from AWS.
[Update your terraform](https://developer.hashicorp.com/terraform/install)
`cd infrastructure && terraform init -reconfigure && ./run_terraform.sh plan`
Up to date and no changes are flagged on plan
N/A

Terraform: Wrap role_arn in assume_role

---

api/package.json
api/scripts/holiday_closure_test.ts

The logic that generates dates for the date picker dropdown (items request) now live across applications.
This script can be run to easily check what dates will be listed on any given day
Set `dateNow` as the date you want to test
Run `yarn check_holiday_closures`
We're confident that the date picker will display correct dates over the holiday closure
If the logic changes in the catalogue-api, this script will need updating too

script to test end of year closure in date picker

---

.buildkite/pipeline.yml
api/config.ts
api/scripts/holiday_closure_test.ts
pipeline/src/handler.ts
pipeline/src/local.ts
pipeline/test/extractTransformLoad.test.ts
unpublisher/src/local.ts

☝️ 
Makes the new pipeline (`2024-12-10`) the one that the Content API is pointing at.
Not sure – run all the tests?
We have addressables in the content api
Something breaks. We have to switch back over to the old pipeline (which we're not removing until we're happy with everything, so should be ok).

Point to new pipeline

---

pipeline/src/transformers/addressables/article.ts
pipeline/src/transformers/addressables/book.ts
pipeline/src/transformers/addressables/event.ts
pipeline/src/transformers/addressables/exhibition.ts
pipeline/src/transformers/addressables/exhibitionHighlightTour.ts
pipeline/src/transformers/addressables/exhibitionText.ts
pipeline/src/transformers/addressables/page.ts
pipeline/src/transformers/addressables/project.ts
pipeline/src/transformers/addressables/season.ts
pipeline/src/transformers/addressables/visualStory.ts
pipeline/src/transformers/article.ts
pipeline/src/transformers/utils.ts

We had a lot of repeated code to get the caption from a promo image. This adds a helper to get the caption.
`cd pipeline && yarn test` – snapshots still pass
We have fewer places for bugs to be introduced and a more straightforward path for updating the logic in future if necessary.
This is the first time I've looked at a code editor since 2024.

Move caption/description logic into a helper

---

pipeline/src/helpers/getGraphQuery.ts
pipeline/src/scripts/documentIds.ts
pipeline/src/scripts/testGraphQuery.ts
pipeline/src/scripts/testTransformer.ts
pipeline/test/update-prismic-snapshots.ts

[Gareth's work here](https://github.com/wellcomecollection/content-api/pull/177/files#diff-33957a3cb92ea5451826ae598642e42bf69c37c6a6bbcff8f9505f544d2b9157), where he rightly reused existing helpers made me realise that we were repeating some logic and defaults IDs at various points. I wanted to streamline it, make it potentially easier to add new types to (although when will that ever happen 😄 ). Would recommend [reviewing without whitespace](https://github.com/wellcomecollection/content-api/pull/194/files?diff=split&w=1).
- Streamlines the test scripts to have one source of truth for default IDs
- Fixes the allowedtypes type, which wasn't working, we could enter whatever value and it would work
I do think it helps with readability and maintainability as well.
Run some tests scripts, see …

Streamline the test scripts

---

infrastructure/ci_iam.tf
infrastructure/pipeline.tf

We deleted the old pipeline (og!) in December but didn't remove it from the code. This is that.
The resource change is because it was pointing to the old pipeline, we've now made it a wildcard so it applies to all.
Run terraform plan, are any changes coming up? (should not)
Code up to date
N/A if nothing comes up in plan.

Remove old pipeline and add wildcard to resource

---

.buildkite/pipeline.yml
api/config.ts
api/scripts/holiday_closure_test.ts
pipeline/src/local.ts
unpublisher/src/local.ts

Move everything over to using the new pipeline (for #123)
Unsure for the live pipeline, but you could run it locally and test out reindexes etc.
New events relevancy parameters are live
Well I haven't really done this before so that's a risk, but a chance to amend the README for next time 😄

Change to pipeline 2025-01-20

---

infrastructure/README.md
infrastructure/pipeline.tf

#201 
Removes the old pipeline as the API [uses the new one](https://api.wellcomecollection.org/content/v0/_elasticConfig) since Friday and no problems have come up.
I've already destroyed the old pipeline with a targeted destroy so this just ensure `main` is up-to-date, as well as updates the README instructions based on what I ran into when doing this work!
Does the README make sense? 
Does running `terraform plan` flag any changes?
We now have everything we need to create/destroy pipelines on our own next time.
N/A already applied

Update README on how to delete a pipeline and remove old pipeline module

---

api/package.json

Part of https://github.com/wellcomecollection/wellcomecollection.org/pull/11551
This change updates the port that content API uses when run locally in order that it can run at the same time locally to enable a more complete local development experience when working with https://github.com/wellcomecollection/wellcomecollection.org
- In the `./api` folder run:
- `yarn && yarn dev`
The content API should be available on `localhost:3002`.
This change can be more thoroughly tested by reviewing https://github.com/wellcomecollection/wellcomecollection.org/pull/11551 and following the relevant steps described running this branch.
Easier development!
This should have minimal impact as there are no prod changes, and the correct port is flagged to devs when the app starts.

Update ports to use local nginx for dev

---

infrastructure/pipeline.tf

Add new pipeline module
It's been deployed already - you can find it on ES and AWS.
Merging this would just ensure we have the newest config in `main`.

Create new pipeline 2025-02-06

---

.buildkite/pipeline.yml
api/config.ts
api/scripts/holiday_closure_test.ts
api/src/queries/articles.ts
api/src/queries/events.ts
api/test/__snapshots__/query.test.ts.snap
infrastructure/README.md
pipeline/src/indices/articles.ts
pipeline/src/indices/events.ts
pipeline/src/local.ts
pipeline/src/transformers/article.ts
pipeline/src/transformers/eventDocument.ts
pipeline/src/types/transformed/index.ts
pipeline/test/transformers/__snapshots__/article.test.ts.snap
pipeline/test/transformers/__snapshots__/eventDocument.test.ts.snap
unpublisher/src/local.ts

> [!WARNING]
> DO NOT MERGE THIS UNTIL WE ARE READY TO GO AHEAD WITH THE NEW PIPELINE.
> This changes the mapping and the transformer, which won't work with the current pipeline.
Added Paul as a reviewer as he's the consultant on the work; but @wellcomecollection/digital-experience approval will be necessary too ✨ 
#121 
Removes the notion of "Ids" in filter names
See ticket for more information, [starting at this comment](https://github.com/wellcomecollection/content-api/issues/121#issuecomment-2633614082).
If you run it locally, passing in query params, does the API still return the same thing as production?
Aligned with our principles and better to be built upon.
It breaks search! But we'll be able to test this locally and in staging first.

Align filters names for events and articles

---

infrastructure/README.md
infrastructure/create_pipeline.sh
infrastructure/pipeline.tf

The README instructions weren't 100% working (couldn't set required variables and then run scripts, they had to be declared every time). So I also created a bash script to create pipelines and removed the instructions from the README.
Basically I don't really know what I'm doing with this, it's my first time! I tried to put in some validation, but I'd welcome any improvement suggestions/corrections/telling off about it! Thank you!
Create a new pipeline I guess? I've run it locally and it does the job, happy to help with the reviewing/testing process.
Easier/faster to create new pipelines.
Again it's my first time with this, so potentially there are risks, yes.

Add pipeline `2025-02-26` , creation script and modify README

---

infrastructure/README.md
infrastructure/pipeline.tf

For #231 
Deletes the old pipeline
n/a
Old modules aren't hanging around
n/a

Remove pipeline_2025-02-17

---

api/src/controllers/events.ts
api/src/controllers/utils.ts
api/src/helpers/responses.ts
api/src/queries/events.ts
api/src/queries/faceting.ts
api/test/__snapshots__/query.test.ts.snap
api/test/query.test.ts

#220 
Finding out that our code is extremely optimised/clever about reutilising transformers for all of our filters and aggregations, but since `timespan`/Date filter has very different requirements, adding it is very difficult. 
- The demand does seem to have been simplified from the original ticket demands as the only filters we will want are:
1. All
2. Past
3. Future
4. Current
* Ignoring this one for now but might be good to keep in mind, we'll add it same time as exhibitions, I think next quarter. This is good to not as it'll compare the start AND end date, whereas the other ones only care about the end date.
- This filter will be our first RADIO BUTTON filter; so **only one value will be passed/allowed at a time**.
- Events can have multiple dates, which is why we've mapped the …

Timespan aggregation

---

api/src/controllers/articles.ts
api/src/controllers/events.ts
api/src/controllers/validation.ts

We were getting [a lot of errors in the alerts channel](https://wellcome.slack.com/archives/CQ720BG02/p1744963470565019) because bad values were passed in the Content API's filters (e.g. `1'"` as an audience...), which returns a 500 and logs in the channel.
I added a validator for Prismic Ids (which also account for the few uuids we pass in the Content API), which will at least check that only alphanumerical values are passed in and return a more useful error message as "Bad Request". 
I also added a paramsValidator to `articles`, including a date checker (for `YYYY-MM-DD`, which according to tests (query.test.ts) is what we want from a date). We don't currently use Dates as a filter in articles, but we'll be covered when we do.
Results in;
The FE still returns it as a "Content API …

Add validation on Prismic filter values as well as dates

---

api/package.json
pipeline/src/types/prismic/exhibitionHighlightTours.ts
pipeline/src/types/prismic/exhibitionTexts.ts
yarn.lock

This should address the [High security alert](https://github.com/wellcomecollection/content-api/security/dependabot/38) we get for `path-to-regexp`, it is a dependency of `express` and `express@5` uses `path-to-regexp@8`. 
I followed [the migration guide](https://expressjs.com/en/guide/migrating-5.html) and had a look at how we use it - it seems unaffected. I was able to run the API locally.
I ran a fresh `yarn` to make sure a brand new file wouldn't break things and a few TS flags came up which I've addressed here.
Run locally too? Remove all modules and lock files and re-run `yarn`; does everything still behave as expected?
No more vulnerabilities
N/A

Upgrade `express` to v5

---

.github/workflows/tsc.yml

My first Copilot PR ✨ 🙃 
Potential fix for [https://github.com/wellcomecollection/content-api/security/code-scanning/1](https://github.com/wellcomecollection/content-api/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the workflow level (applies to all jobs) to explicitly set the permissions to `contents: read`. This is sufficient for the current workflow, as it only checks out the repository and installs dependencies without requiring any write access.
The `permissions` block will be added after the `name` field at the top of the workflow file.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

infrastructure/pipeline_stack/scheduled_window_event.tf

For https://github.com/wellcomecollection/content-api/issues/265
Adds a new AWS EventBridge scheduler to run daily, reindexing all of the addressables content. 
Ensures all addressables content is fully reprocessed daily, catching any changes to linkedWorks data.
See [handling changes to works](https://github.com/wellcomecollection/docs/tree/main/rfcs/077-enriching-addressables-with-works#handling-changes-to-works) for details.

Add daily reindexing scheduler for addressables

---

.buildkite/pipeline.yml

(should) trigger .org e2es after deploying to staging. This ensures our changes do not affect the website before we deploy to production.
I don't think we can until we merge? Ideas?
Catches bugs !
N/A

Run .org e2es when merging to staging
