wellcomecollection/content-api

- infrastructure/.terraform.lock.hcl
- infrastructure/cluster.tf
- infrastructure/ecr.tf
- infrastructure/locals.tf
- infrastructure/main.tf
- infrastructure/modules/service_with_sidecar/iam.tf
- infrastructure/modules/service_with_sidecar/main.tf
- infrastructure/modules/service_with_sidecar/outputs.tf
- infrastructure/modules/service_with_sidecar/variables.tf
- infrastructure/providers.tf
- infrastructure/stack/api_service.tf
- infrastructure/stack/nlb.tf
- infrastructure/stack/security_groups.tf
- infrastructure/stack/variables.tf
- infrastructure/terraform.tf
Part of https://github.com/wellcomecollection/content-api/issues/2
Doesn't include API Gateway or CloudFront or any deployment stuff.
This is largely copied from the catalogue-api repo (although I'm trying to keep the directory structure flatter and simpler, because it's been confusing to find where things live in there)
> ECS service behind a load balancer

- infrastructure/locals.tf
- infrastructure/main.tf
- infrastructure/modules/api_route/main.tf
- infrastructure/modules/api_route/outputs.tf
- infrastructure/modules/api_route/variables.tf
- infrastructure/providers.tf
- infrastructure/stack/api_gateway.tf
- infrastructure/stack/certificate.tf
- infrastructure/stack/nlb.tf
- infrastructure/stack/providers.tf
- infrastructure/stack/variables.tf
Part of https://github.com/wellcomecollection/content-api/issues/2
This is almost entirely copied from the catalogue API repo
> API Gateway

- .buildkite/pipeline.yml
- builds/deploy_ecs_services.sh
- builds/update_ecr_image_tag.sh
Part of https://github.com/wellcomecollection/content-api/issues/2
Publishes images to ECR and deploys them to stage on merges to `main`.
> CI Deployment

- api/jest.config.js
- api/tsconfig.json
- common/package.json
- common/tsconfig.json
- package.json
- pipeline/jest.config.js
- pipeline/package.json
- pipeline/src/handler.ts
- pipeline/src/helpers/elasticsearch.ts
- pipeline/src/helpers/observableToStream.ts
- pipeline/src/helpers/prismic.ts
- pipeline/tsconfig.build.json
- pipeline/tsconfig.json
- tsconfig.base.json
Also sorts out some typescript nonsense (I think)
> Initial streaming indexing of articles

- api/package.json
- pipeline/src/handler.ts
- pipeline/src/helpers/elasticsearch.ts
- pipeline/src/helpers/prismic.ts
- pipeline/src/mappings/articles.ts
- pipeline/src/transformers/article.ts
- pipeline/src/types/index.ts
- yarn.lock
I could add more later on, such as the analyzers in settings and the `fields` sections in the mapping.
Could also add `body` and `standfirst` in the next PR.
You can run `GET /testing/_mapping` to see the current state.
Currently results in:
```
{
"_index": "testing",
"_id": "ZBhbrxQAAB3yH6W6",
"_version": 1,
"_seq_no": 0,
"_primary_term": 1,
"found": true,
"_source": {
"id": "ZBhbrxQAAB3yH6W6",
"display": {
"type": "Article",
"id": "ZBhbrxQAAB3yH6W6",
"title": "Translation",
"caption": "It can be OK to ask a direct question… sometimes skirting around the topic of cancer can make it the elephant in the room that hangs around awkwardly.",
"format": {
"type": "ArticleFormat",
"id": "W7d_ghAAALWY3Ujc",
"label": "Comic"
},
"publicationDate": "2023-03-31T09:00:00+0000",
"contributors": [
{ …
```
> Add basic mapping for query

- infrastructure/api_stack/api_service.tf
> Provide required APM config to the API

- api/src/controllers/articles.ts
Based off of [Harrison's prototype](https://github.com/wellcomecollection/data-science/blob/main/prismic-pipeline-prototype/data/queries/articles.json) with a few tweaks (renamed fields to match and changed `minimum_should_match` at his request.
> API Query config

- infrastructure/pipeline.tf
- infrastructure/pipeline_stack/scheduled_window_event.tf
- infrastructure/pipeline_stack/variables.tf
- pipeline/package.json
- pipeline/src/event.ts
- pipeline/src/handler.ts
- pipeline/src/helpers/elasticsearch.ts
- pipeline/src/helpers/prismic.ts
- pipeline/src/local.ts
- pipeline/test/event.test.ts
- yarn.lock
Resolves https://github.com/wellcomecollection/content-api/issues/38
> Fetch articles on schedule

- infrastructure/locals.tf
- infrastructure/pipeline.tf
- infrastructure/pipeline_stack/lambda.tf
- infrastructure/pipeline_stack/variables.tf
- infrastructure/terraform.tf
For https://github.com/wellcomecollection/content-api/issues/37
> Hook up lambda to error alerting

- api/src/controllers/articles.ts
- infrastructure/pipeline_stack/elastic_cluster.tf
> Handle too_many_nested_clauses errors from ES

- api/src/controllers/articles.ts
https://wellcome.slack.com/archives/C02ANCYL90E/p1684320449602619
There is no field in the responses at `publication.dates` - perhaps we got something mixed up with an earlier version of the API RFC - so I have added the correct sort key `publicationDate` and will remove the incorrect one once the frontend is updated.
> Recency is relevant

- api/jest.config.js
- api/package.json
- api/src/controllers/articles.ts
- api/src/controllers/validation.ts
- api/src/helpers/index.ts
- api/src/queries/articles.ts
- api/test/global.d.ts
- api/test/setup.js
- api/test/validation.test.ts
- pipeline/src/indices/articles.ts
- pipeline/src/transformers/article.ts
- pipeline/src/types/index.ts
- pipeline/test/transformers/__snapshots__/article.test.ts.snap
To be followed by aggregations
Part of https://github.com/wellcomecollection/content-api/issues/48
> Add filters for contributors, formats, and publication dates

- pipeline/package.json
- pipeline/src/helpers/index.ts
- pipeline/src/helpers/prismic.ts
- pipeline/src/helpers/type-guards.ts
- pipeline/src/transformers/article.ts
- pipeline/src/types/prismic/articles.ts
- pipeline/src/types/prismic/body.ts
- pipeline/src/types/prismic/contributors.ts
- pipeline/src/types/prismic/formats.ts
- pipeline/src/types/prismic/images.ts
- pipeline/src/types/prismic/index.ts
- pipeline/src/types/prismic/series.ts
- pipeline/test/fixtures/prismic-snapshots.ts
- pipeline/test/fixtures/prismic.ts
- pipeline/test/prismic-helpers.test.ts
- yarn.lock
Follows #53
Closes https://github.com/wellcomecollection/wellcomecollection.org/issues/9797
> Upgrade to v7 of the @prismicio/client library

- api/src/controllers/articles.ts
- api/src/queries/faceting.ts
- api/test/__snapshots__/query.test.ts.snap
- api/test/faceting.test.ts
- api/test/query.test.ts
I was rather pleased with myself after https://github.com/wellcomecollection/content-api/pull/51 - but I shouldn't have been, I got it wrong. The test cases should adequately illustrate what the misunderstanding was...
> Correct understanding of faceting

- api/src/queries/faceting.ts
- api/test/faceting.test.ts
Should resolve the infuriating issue described in https://github.com/wellcomecollection/wellcomecollection.org/issues/10028#issuecomment-1635708292
> Always rewrite aggregations to include self-filters 

- api/src/helpers/responses.ts
- api/test/responses.test.ts
> There is no ambiguity if multiple filters are applied

- .buildkite/pipeline.yml
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/410
Same issue was found in the concept pipeline, and fixed in the same way 
https://wellcome.slack.com/archives/C02ANCYL90E/p1702563277030749
> use cli-version 2 with docker-compose#v4.11.0 plugin

- api/src/controllers/events.ts
- pipeline/src/indices/events.ts
Sorts #84 
Start times added to index mapping and functionality to `sort` added into the events controller.
> Sort events by startDateTime

- .github/workflows/stale.yml
Resetting the schedule to what it should be now that we've seen it work 👀
also, go get the workflow from `main` instead of the testing branch
N/A
Should have run tomorrow morning when we log on
N/A
> reset schedule to once a day Mon-Thu

- infrastructure/pipeline.tf
> Remove old pipeline

- infrastructure/pipeline.tf
> Add new pipeline (2025-02-17)

- infrastructure/pipeline.tf
#223 
Already applied, `plan` output:
> Remove pipeline 2025-02-06 from codebase

- infrastructure/README.md
- infrastructure/pipeline.tf
Allows for work in [Review whether or not ordering works as expected](https://github.com/wellcomecollection/content-api/issues/241)
Already applied
> Added module pipeline 2025-04-14, updated README

- infrastructure/pipeline.tf
> Add 2025-05-07 pipeline

- infrastructure/pipeline.tf
> delete pipeline 2022-04-14

- .github/dependabot.yml
Updated package ecosystem for npm and added GitHub Actions updates.
Copied from .org, changed frequency to monthly checks
> Configure Dependabot for npm and GitHub Actions
